version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c0a5fb1 (up)

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
<<<<<<< HEAD
=======
>>>>>>> 95a4930 (.)
=======
>>>>>>> c0a5fb1 (up)
